
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN BEGIN COLON DIVIDE DOT END ID INTEGER LPAREN MINUS NUMBER PLUS PROGRAM RPAREN SEMI TIMES VAR WRITEprogram : PROGRAM ID SEMI block DOTblock : VAR declarations BEGIN statements ENDdeclarations : declarations declaration\n                    | declarationdeclaration : ID COLON INTEGER SEMIstatements : statements statement\n                  | statementstatement : ID ASSIGN expression SEMI\n                 | WRITE LPAREN expression RPAREN SEMIexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expressionexpression : LPAREN expression RPARENexpression : NUMBERexpression : ID'
    
_lr_action_items = {'PROGRAM':([0,],[2,]),'$end':([1,7,],[0,-1,]),'ID':([2,6,8,9,11,12,14,15,20,21,22,23,26,29,30,31,32,33,41,],[3,10,10,-4,16,-3,16,-7,-6,24,24,-5,24,-8,24,24,24,24,-9,]),'SEMI':([3,18,24,25,27,35,36,37,38,39,40,],[4,23,-16,29,-15,41,-10,-11,-12,-13,-14,]),'VAR':([4,],[6,]),'DOT':([5,19,],[7,-2,]),'BEGIN':([8,9,12,23,],[11,-4,-3,-5,]),'COLON':([10,],[13,]),'WRITE':([11,14,15,20,29,41,],[17,17,-7,-6,-8,-9,]),'INTEGER':([13,],[18,]),'END':([14,15,20,29,41,],[19,-7,-6,-8,-9,]),'ASSIGN':([16,],[21,]),'LPAREN':([17,21,22,26,30,31,32,33,],[22,26,26,26,26,26,26,26,]),'NUMBER':([21,22,26,30,31,32,33,],[27,27,27,27,27,27,27,]),'PLUS':([24,25,27,28,34,36,37,38,39,40,],[-16,30,-15,30,30,30,30,30,30,-14,]),'MINUS':([24,25,27,28,34,36,37,38,39,40,],[-16,31,-15,31,31,31,31,31,31,-14,]),'TIMES':([24,25,27,28,34,36,37,38,39,40,],[-16,32,-15,32,32,32,32,32,32,-14,]),'DIVIDE':([24,25,27,28,34,36,37,38,39,40,],[-16,33,-15,33,33,33,33,33,33,-14,]),'RPAREN':([24,27,28,34,36,37,38,39,40,],[-16,-15,35,40,-10,-11,-12,-13,-14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'block':([4,],[5,]),'declarations':([6,],[8,]),'declaration':([6,8,],[9,12,]),'statements':([11,],[14,]),'statement':([11,14,],[15,20,]),'expression':([21,22,26,30,31,32,33,],[25,28,34,36,37,38,39,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> PROGRAM ID SEMI block DOT','program',5,'p_program','parser.py',34),
  ('block -> VAR declarations BEGIN statements END','block',5,'p_block','parser.py',41),
  ('declarations -> declarations declaration','declarations',2,'p_declarations','parser.py',45),
  ('declarations -> declaration','declarations',1,'p_declarations','parser.py',46),
  ('declaration -> ID COLON INTEGER SEMI','declaration',4,'p_declaration','parser.py',53),
  ('statements -> statements statement','statements',2,'p_statements','parser.py',62),
  ('statements -> statement','statements',1,'p_statements','parser.py',63),
  ('statement -> ID ASSIGN expression SEMI','statement',4,'p_statement','parser.py',70),
  ('statement -> WRITE LPAREN expression RPAREN SEMI','statement',5,'p_statement','parser.py',71),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','parser.py',86),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','parser.py',87),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','parser.py',88),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','parser.py',89),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','parser.py',99),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser.py',103),
  ('expression -> ID','expression',1,'p_expression_var','parser.py',107),
]
